services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: helpdesk-db
    environment:
      SA_PASSWORD: Zumiezlover47!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
    ports:
      - "5127:5127"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=db;Database=HelpDeskTicketsDB;User Id=sa;Password=Zumiezlover47!;TrustServerCertificate=True
    depends_on:
      - db

  web:
    build:
      context: ./helpdesk-ui
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:5127
    depends_on:
      - api

volumes:
  sql_data: